name: Jobs
main: de.petropia.spacelifeJobs.Jobs
version: 1.0.0
author: Professor_Sam
api-version: 1.19
depend:
  - "TurtleServer"
  - "SpacelifeCore"
commands:
  jobs:
    aliases: berufe
    description: "Öffnet Job gui"
permissions:
  spacelife.jobs.command.job.clear:
    default: false